FROM ubuntu:24.04

RUN apt-get update && apt-get install -y golang-go ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o /test ./tests/docker/test.go

CMD ["/test"]
